OnlineProject/Models/Customers.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OnlineProject.Models
{
    public class Customers
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        
    }
}

OnlineProject/Models/ErrorViewModel.cs
namespace OnlineProject.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

OnlineProject/Models/Products.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OnlineProject.Models
{
    public class Products
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public int Price { get; set; }
        public string Brand { get; set; }

        [ForeignKey("Customers")]
        public int CustomerId { get; set; }
        public virtual Customers Customers { get; set; }
    }
}

OnlineProject/Models/Signup.cs
using System.ComponentModel.DataAnnotations;

namespace OnlineProject.Models
{
    public class Signup
    {
        [Key]
        
        public int sId { get; set; }
        [Required(ErrorMessage="Please Enter a valid Name")]
        [StringLength(20),MinLength(5)]
        public string Name { get; set; }
        [Required(ErrorMessage ="Please Enter a valid Address")]
        [StringLength(30,MinimumLength=5)]
        public string Address { get; set; }
        [Required(ErrorMessage = "Please Enter a Phone number")]
        [RegularExpression(@"^98[0-9]{8}$")]
        [StringLength(10, ErrorMessage = "Phone number must be 10 digit"),MinLength(10)]

        public string Phone { get; set; }
        [Required(ErrorMessage ="Please Enter a valid Email")]
        [EmailAddress]
        public string Email { get; set; }
        [Required (ErrorMessage ="Please Enter a valid Password")]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[#$^+=!*()@%&]).{8,}$")]
        public string Password { get; set; }
        [Required (ErrorMessage ="Your password doesnot match")]
        [Compare("Password")]
        public string CPassword { get; set; }
        [Required(ErrorMessage = "You are missing this field")]
        public Gender Gender { get; set; }
            
    }

    public enum Gender
    {
        Male, Female, Others
    }
}

OnlineProject/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineProject.Models;
using System.Diagnostics;

namespace OnlineProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

OnlineProject/Controllers/SignupController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineProject.Models;
using OnlineProject.Data;
using Microsoft.Extensions.Options;
using Microsoft.EntityFrameworkCore;
using OnlineProject.Migrations;
using OnlineProject.Data;

namespace OnlineProject.Controllers
{
    public class SignupController : Controller 
    { 
        private readonly OnlineProjectContext _context;
        public SignupController(OnlineProjectContext context)
        {
            _context = context;
        }
              
             public IActionResult Index()
             {
            var data = _context.Signups.ToList();
              return View(data);
             }

            [HttpGet]
            public IActionResult Form( )
            {
              return View();
            }
            [HttpPost]
            public IActionResult Form(Signup s)
            {
                _context.Signups.Add(s);
                 _context.SaveChanges();
                return View();
            }

         
    }
}

OnlineProject/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

OnlineProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OnlineProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OnlineProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - OnlineProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

OnlineProject/Views/Signup/Form.cshtml
@model Signup 
<form asp-action="Form" asp-controller="Signup" method="post">
   <div>
        <label asp-for="Name" class="form-label" ></label>
        <input asp-for="Name" class="form-control">
    </div>
        <div>
             <label asp-for="Address" class="form-label"></label>
             <input asp-for="Address" class="form-control">
         </div>
    <div>
        <label asp-for="Phone" class="form-label"></label>
          <input asp-for="Phone" class="form-control">
    </div>
   
    <div>

        <label asp-for="Gender" class="form-label"></label>
         <select asp-for="Gender" class="form-control" asp-items="Html.GetEnumSelectList<Gender>()">
             <option value="">SelectGender</option>
         </select>

    </div>
    <div>
        <label asp-for="Email" class="form-label"></label>
        <input asp-for="Email" class="form-control">
    </div>
   <div>
       <label asp-for="Password"class="form-label"></label>
        <input asp-for="Password" class="form-control">
    </div>
    <div>
        <label asp-for="CPassword"class="form-label"></label>
         <input asp-for="CPassword"class="form-control">
    </div>
    <div>
        <input type="submit" value="Submit" class="btn-outline-primary" />
     </div>
</form>

OnlineProject/Views/Signup/Index.cshtml
@model List<Signup>
<form asp-action="Index" method="get" asp-controller="Signup">
    <table class="table table-striped table-bordered table-hover">
        <thead class="thead-dark ">
             <tr>
                <th>Name</th>
                <th>Address</th>
                <th>Phone</th>
                <th>Gender</th>
                <th>Email</th>
            </tr>
        </thead>
        <tbody class="thead-light">
            @foreach(var item in Model)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.Address</td>
                    <td>@item.Phone</td>
                    <td>@item.Gender</td>
                    <td>@item.Email</td>
                </tr>
            }
        </tbody>
     
    </table>
</form>